### ISSUE TITLE
Question about LICENSE & state of this project

### ISSUE THREAD

**Issue by ken0x0a** [mrphu3074/flutter_easy_validator#1]
I found, this project is awesome.
Thank you for your great work!!

I have 1 request and 1 question.

### Request
Could you specify the license?
I'm happy if it will be MIT or Apache 2.0 or ....

### Question
Is this ready to use, or still work in progress?
As I can see "release 1.0.0", I originally thought it's ready to use.
But I'm confused as I couldn't find on pub.dev.

**Comment by mrphu3074** [comment]
hi @ken0x0a, this lib created for internal use, and did not touch for a long time. I have a plan to maintain this library this year (upgrade, improvement, documentation, ...)

About the license, it should be Apache 2.0.

> Is this ready to use, or still work in progress?

This lib used in many internal apps, but please test it carefully before using it in the production app.

thanks.
